
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


logging:
  file:
    name: logs/api.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    br.com.dbccompany.vemser.Controller: ERROR
    org.hibernate: WARN

---

mail:
  host: smtp.gmail.com
  port: 587
  username: retrocards2020@gmail.com
  password: cbdcbd2020vemser*
  protocol: smtp
  tls: true
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com
